name: Deploy to MonsterASP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore EventHub.sln

      - name: Publish
        run: dotnet publish ./EventHub/EventHub.csproj -c Release -o ./publish

      - name: Take app offline
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./.github/offline/
          server-dir: /wwwroot/

      - name: Wait for IIS to release file locks
        run: sleep 10

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./publish/
          server-dir: /wwwroot/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
